import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { poppins } from '@/app/ui/fonts';

import ScrollHide from "./tools/scrollHide";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${poppins.className} antialiased bg-black text-white`}>
      <Navbar />
      {children}
      <Footer/>

      <ScrollHide /> 
    </body>
  </html>
  );
}
